cmake_minimum_required(VERSION 4.2)
project(EstudosC C)

set(CMAKE_C_STANDARD 11)

add_executable(EstudosC
        C-Aulas/estruturas_condicional/condicional_compota.c
        C-Aulas/estruturas_condicional/condicional_simples.c
        C-Aulas/estruturas_condicional/estrutura_caso.c
        C-Aulas/estruturas_condicional/problema1.c
        C-Aulas/estruturas_condicional/problema2.c
        C-Aulas/estruturas_condicional/problema3.c
        C-Aulas/estruturas_condicional/problema4.c
        C-Aulas/estruturas_condicional/problema5.c
        C-Aulas/estruturas_de_dados/pilhas/pilha.c
        C-Aulas/estruturas_de_dados/ponteiros/exemplo1.c
        C-Aulas/estruturas_de_dados/ponteiros/exemplo2.c
        C-Aulas/estruturas_de_dados/ponteiros/exemplo3.c
        C-Aulas/estruturas_de_dados/ponteiros/exemplo4.c
        C-Aulas/estruturas_de_dados/ponteiros/exemplo5.c
        C-Aulas/estruturas_repeticao/desafios/d1.c
        C-Aulas/estruturas_repeticao/exemplo1_for.c
        C-Aulas/estruturas_repeticao/exemplo2_while.c
        C-Aulas/estruturas_repeticao/exemplo3_do_while.c
        C-Aulas/estruturas_repeticao/problema1.c
        C-Aulas/estruturas_repeticao/problema2.c
        C-Aulas/estruturas_repeticao/problema3.c
        C-Aulas/estruturas_repeticao/problema4.c
        C-Aulas/estruturas_repeticao/problema5.c
        C-Aulas/estruturas_repeticao/problema6.c
        C-Aulas/estruturas_repeticao/problema7.c
        C-Aulas/estruturas_repeticao/problema8.c
        C-Aulas/funcoes/exemplo1.c
        C-Aulas/funcoes/exemplo2.c
        C-Aulas/primeiros_codigos/constantes.c
        C-Aulas/primeiros_codigos/desafio1.c
        C-Aulas/primeiros_codigos/formatacao_texto.c
        C-Aulas/primeiros_codigos/leitura_de_dados.c
        C-Aulas/primeiros_codigos/ola-mundo.c
        C-Aulas/primeiros_codigos/problema1.c
        C-Aulas/primeiros_codigos/problema2.c
        C-Aulas/primeiros_codigos/problema3.c
        C-Aulas/primeiros_codigos/problema4.c
        C-Aulas/primeiros_codigos/problema5.c
        C-Aulas/projeto-mapa/arquivo.c
        C-Aulas/structs/exemplo1.c
        C-Aulas/vetores/exemplo1.c
        C-Aulas/vetores/exemplo2.c
        C-Aulas/vetores/exemplo3.c
        C-Aulas/vetores/teste.c
        Exercicios/ex01.c
        Exercicios/ex010.c
        Exercicios/ex011.c
        Exercicios/ex012.c
        Exercicios/ex013.c
        Exercicios/ex014.c
        Exercicios/ex015.c
        Exercicios/ex017.c
        Exercicios/ex018.c
        Exercicios/ex019.c
        Exercicios/ex02.c
        Exercicios/ex020.c
        Exercicios/ex021.c
        Exercicios/ex022.c
        Exercicios/ex023.c
        Exercicios/ex024.c
        Exercicios/ex025.c
        Exercicios/ex03.c
        Exercicios/ex04.c
        Exercicios/ex05.c
        Exercicios/ex06.c
        Exercicios/ex07.c
        Exercicios/ex08.c
        Exercicios/ex09.c
        C-Aulas/estruturas_de_dados/filas/fila.c
        C-Aulas/estruturas_de_dados/lista-dinamica/lista_dinamica.c
        Exercicios/ex026.c
        Exercicios/ex027.c
        Exercicios/ex028.c)
